//go:build !ignore_autogenerated

/*
Copyright 2026 Raj Singh.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminConfig) DeepCopyInto(out *AdminConfig) {
	*out = *in
	if in.AdminTokenSecretRef != nil {
		in, out := &in.AdminTokenSecretRef, &out.AdminTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricsTokenSecretRef != nil {
		in, out := &in.MetricsTokenSecretRef, &out.MetricsTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminConfig.
func (in *AdminConfig) DeepCopy() *AdminConfig {
	if in == nil {
		return nil
	}
	out := new(AdminConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockConfig) DeepCopyInto(out *BlockConfig) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.RAMBufferMax != nil {
		in, out := &in.RAMBufferMax, &out.RAMBufferMax
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxConcurrentReads != nil {
		in, out := &in.MaxConcurrentReads, &out.MaxConcurrentReads
		*out = new(int)
		**out = **in
	}
	if in.MaxConcurrentWritesPerRequest != nil {
		in, out := &in.MaxConcurrentWritesPerRequest, &out.MaxConcurrentWritesPerRequest
		*out = new(int)
		**out = **in
	}
	if in.CompressionLevel != nil {
		in, out := &in.CompressionLevel, &out.CompressionLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockConfig.
func (in *BlockConfig) DeepCopy() *BlockConfig {
	if in == nil {
		return nil
	}
	out := new(BlockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockErrorDetail) DeepCopyInto(out *BlockErrorDetail) {
	*out = *in
	if in.LastAttempt != nil {
		in, out := &in.LastAttempt, &out.LastAttempt
		*out = (*in).DeepCopy()
	}
	if in.NextRetry != nil {
		in, out := &in.NextRetry, &out.NextRetry
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockErrorDetail.
func (in *BlockErrorDetail) DeepCopy() *BlockErrorDetail {
	if in == nil {
		return nil
	}
	out := new(BlockErrorDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockErrorsStatus) DeepCopyInto(out *BlockErrorsStatus) {
	*out = *in
	if in.LastErrorAt != nil {
		in, out := &in.LastErrorAt, &out.LastErrorAt
		*out = (*in).DeepCopy()
	}
	if in.TopErrors != nil {
		in, out := &in.TopErrors, &out.TopErrors
		*out = make([]BlockErrorDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockErrorsStatus.
func (in *BlockErrorsStatus) DeepCopy() *BlockErrorsStatus {
	if in == nil {
		return nil
	}
	out := new(BlockErrorsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEndpoints) DeepCopyInto(out *ClusterEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEndpoints.
func (in *ClusterEndpoints) DeepCopy() *ClusterEndpoints {
	if in == nil {
		return nil
	}
	out := new(ClusterEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealth) DeepCopyInto(out *ClusterHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealth.
func (in *ClusterHealth) DeepCopy() *ClusterHealth {
	if in == nil {
		return nil
	}
	out := new(ClusterHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
	if in.KubeConfigSecretRef != nil {
		in, out := &in.KubeConfigSecretRef, &out.KubeConfigSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStorageStats) DeepCopyInto(out *ClusterStorageStats) {
	*out = *in
	if in.TotalCapacity != nil {
		in, out := &in.TotalCapacity, &out.TotalCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.UsedCapacity != nil {
		in, out := &in.UsedCapacity, &out.UsedCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AvailableCapacity != nil {
		in, out := &in.AvailableCapacity, &out.AvailableCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStorageStats.
func (in *ClusterStorageStats) DeepCopy() *ClusterStorageStats {
	if in == nil {
		return nil
	}
	out := new(ClusterStorageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectToConfig) DeepCopyInto(out *ConnectToConfig) {
	*out = *in
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(ClusterReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RPCSecretRef != nil {
		in, out := &in.RPCSecretRef, &out.RPCSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminTokenSecretRef != nil {
		in, out := &in.AdminTokenSecretRef, &out.AdminTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectToConfig.
func (in *ConnectToConfig) DeepCopy() *ConnectToConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectToConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulDiscoveryConfig) DeepCopyInto(out *ConsulDiscoveryConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.CACertSecretRef != nil {
		in, out := &in.CACertSecretRef, &out.CACertSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientCertSecretRef != nil {
		in, out := &in.ClientCertSecretRef, &out.ClientCertSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKeySecretRef != nil {
		in, out := &in.ClientKeySecretRef, &out.ClientKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Meta != nil {
		in, out := &in.Meta, &out.Meta
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Datacenters != nil {
		in, out := &in.Datacenters, &out.Datacenters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulDiscoveryConfig.
func (in *ConsulDiscoveryConfig) DeepCopy() *ConsulDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(ConsulDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPath) DeepCopyInto(out *DataPath) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(DataPathVolumeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPath.
func (in *DataPath) DeepCopy() *DataPath {
	if in == nil {
		return nil
	}
	out := new(DataPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPathVolumeConfig) DeepCopyInto(out *DataPathVolumeConfig) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VolumeClaimTemplateSpec != nil {
		in, out := &in.VolumeClaimTemplateSpec, &out.VolumeClaimTemplateSpec
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPathVolumeConfig.
func (in *DataPathVolumeConfig) DeepCopy() *DataPathVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(DataPathVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.LMDBMapSize != nil {
		in, out := &in.LMDBMapSize, &out.LMDBMapSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.FjallBlockCacheSize != nil {
		in, out := &in.FjallBlockCacheSize, &out.FjallBlockCacheSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryConfig) DeepCopyInto(out *DiscoveryConfig) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesDiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Consul != nil {
		in, out := &in.Consul, &out.Consul
		*out = new(ConsulDiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryConfig.
func (in *DiscoveryConfig) DeepCopy() *DiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(DiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalIPEndpointConfig) DeepCopyInto(out *ExternalIPEndpointConfig) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalIPEndpointConfig.
func (in *ExternalIPEndpointConfig) DeepCopy() *ExternalIPEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalIPEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageBuildInfo) DeepCopyInto(out *GarageBuildInfo) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageBuildInfo.
func (in *GarageBuildInfo) DeepCopy() *GarageBuildInfo {
	if in == nil {
		return nil
	}
	out := new(GarageBuildInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageCluster) DeepCopyInto(out *GarageCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageCluster.
func (in *GarageCluster) DeepCopy() *GarageCluster {
	if in == nil {
		return nil
	}
	out := new(GarageCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GarageCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageClusterDefaulter) DeepCopyInto(out *GarageClusterDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageClusterDefaulter.
func (in *GarageClusterDefaulter) DeepCopy() *GarageClusterDefaulter {
	if in == nil {
		return nil
	}
	out := new(GarageClusterDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageClusterList) DeepCopyInto(out *GarageClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GarageCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageClusterList.
func (in *GarageClusterList) DeepCopy() *GarageClusterList {
	if in == nil {
		return nil
	}
	out := new(GarageClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GarageClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageClusterSpec) DeepCopyInto(out *GarageClusterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Network.DeepCopyInto(&out.Network)
	if in.S3API != nil {
		in, out := &in.S3API, &out.S3API
		*out = new(S3APIConfig)
		**out = **in
	}
	if in.K2VAPI != nil {
		in, out := &in.K2VAPI, &out.K2VAPI
		*out = new(K2VAPIConfig)
		**out = **in
	}
	if in.WebAPI != nil {
		in, out := &in.WebAPI, &out.WebAPI
		*out = new(WebAPIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Admin != nil {
		in, out := &in.Admin, &out.Admin
		*out = new(AdminConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Blocks != nil {
		in, out := &in.Blocks, &out.Blocks
		*out = new(BlockConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(DiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
	if in.PublicEndpoint != nil {
		in, out := &in.PublicEndpoint, &out.PublicEndpoint
		*out = new(PublicEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteClusters != nil {
		in, out := &in.RemoteClusters, &out.RemoteClusters
		*out = make([]RemoteClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LayoutManagement != nil {
		in, out := &in.LayoutManagement, &out.LayoutManagement
		*out = new(LayoutManagementConfig)
		**out = **in
	}
	if in.DefaultNodeTags != nil {
		in, out := &in.DefaultNodeTags, &out.DefaultNodeTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectTo != nil {
		in, out := &in.ConnectTo, &out.ConnectTo
		*out = new(ConnectToConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(MaintenanceSpec)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(WorkersConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageClusterSpec.
func (in *GarageClusterSpec) DeepCopy() *GarageClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GarageClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageClusterStatus) DeepCopyInto(out *GarageClusterStatus) {
	*out = *in
	if in.BuildInfo != nil {
		in, out := &in.BuildInfo, &out.BuildInfo
		*out = new(GarageBuildInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StagedLayoutVersion != nil {
		in, out := &in.StagedLayoutVersion, &out.StagedLayoutVersion
		*out = new(int64)
		**out = **in
	}
	if in.LayoutPreview != nil {
		in, out := &in.LayoutPreview, &out.LayoutPreview
		*out = new(LayoutPreviewStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(ClusterHealth)
		**out = **in
	}
	if in.StorageStats != nil {
		in, out := &in.StorageStats, &out.StorageStats
		*out = new(ClusterStorageStats)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveRepairs != nil {
		in, out := &in.ActiveRepairs, &out.ActiveRepairs
		*out = make([]RepairStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(WorkersStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LayoutHistory != nil {
		in, out := &in.LayoutHistory, &out.LayoutHistory
		*out = new(LayoutHistoryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockErrorDetails != nil {
		in, out := &in.BlockErrorDetails, &out.BlockErrorDetails
		*out = new(BlockErrorsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ScrubStatus != nil {
		in, out := &in.ScrubStatus, &out.ScrubStatus
		*out = new(ScrubStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecycleStatus != nil {
		in, out := &in.LifecycleStatus, &out.LifecycleStatus
		*out = new(LifecycleStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(LastOperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(ClusterEndpoints)
		**out = **in
	}
	if in.RemoteClusters != nil {
		in, out := &in.RemoteClusters, &out.RemoteClusters
		*out = make([]RemoteClusterStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingGatewayTombstones != nil {
		in, out := &in.PendingGatewayTombstones, &out.PendingGatewayTombstones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageClusterStatus.
func (in *GarageClusterStatus) DeepCopy() *GarageClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GarageClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarageClusterValidator) DeepCopyInto(out *GarageClusterValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarageClusterValidator.
func (in *GarageClusterValidator) DeepCopy() *GarageClusterValidator {
	if in == nil {
		return nil
	}
	out := new(GarageClusterValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(VolumeConfig)
		(*in).DeepCopyInto(*out)
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K2VAPIConfig) DeepCopyInto(out *K2VAPIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K2VAPIConfig.
func (in *K2VAPIConfig) DeepCopy() *K2VAPIConfig {
	if in == nil {
		return nil
	}
	out := new(K2VAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesDiscoveryConfig) DeepCopyInto(out *KubernetesDiscoveryConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesDiscoveryConfig.
func (in *KubernetesDiscoveryConfig) DeepCopy() *KubernetesDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastOperationStatus) DeepCopyInto(out *LastOperationStatus) {
	*out = *in
	if in.TriggeredAt != nil {
		in, out := &in.TriggeredAt, &out.TriggeredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastOperationStatus.
func (in *LastOperationStatus) DeepCopy() *LastOperationStatus {
	if in == nil {
		return nil
	}
	out := new(LastOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutHistoryStatus) DeepCopyInto(out *LayoutHistoryStatus) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]LayoutVersionInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutHistoryStatus.
func (in *LayoutHistoryStatus) DeepCopy() *LayoutHistoryStatus {
	if in == nil {
		return nil
	}
	out := new(LayoutHistoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutManagementConfig) DeepCopyInto(out *LayoutManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutManagementConfig.
func (in *LayoutManagementConfig) DeepCopy() *LayoutManagementConfig {
	if in == nil {
		return nil
	}
	out := new(LayoutManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutPreviewStatus) DeepCopyInto(out *LayoutPreviewStatus) {
	*out = *in
	if in.NodesAdded != nil {
		in, out := &in.NodesAdded, &out.NodesAdded
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodesRemoved != nil {
		in, out := &in.NodesRemoved, &out.NodesRemoved
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodesModified != nil {
		in, out := &in.NodesModified, &out.NodesModified
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ZonesAffected != nil {
		in, out := &in.ZonesAffected, &out.ZonesAffected
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutPreviewStatus.
func (in *LayoutPreviewStatus) DeepCopy() *LayoutPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(LayoutPreviewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LayoutVersionInfo) DeepCopyInto(out *LayoutVersionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LayoutVersionInfo.
func (in *LayoutVersionInfo) DeepCopy() *LayoutVersionInfo {
	if in == nil {
		return nil
	}
	out := new(LayoutVersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleStatus) DeepCopyInto(out *LifecycleStatus) {
	*out = *in
	if in.LastCompleted != nil {
		in, out := &in.LastCompleted, &out.LastCompleted
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleStatus.
func (in *LifecycleStatus) DeepCopy() *LifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(LifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerEndpointConfig) DeepCopyInto(out *LoadBalancerEndpointConfig) {
	*out = *in
	in.ServiceMeta.DeepCopyInto(&out.ServiceMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerEndpointConfig.
func (in *LoadBalancerEndpointConfig) DeepCopy() *LoadBalancerEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSpec) DeepCopyInto(out *MaintenanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceSpec.
func (in *MaintenanceSpec) DeepCopy() *MaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.RPCSecretRef != nil {
		in, out := &in.RPCSecretRef, &out.RPCSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RPCPingTimeout != nil {
		in, out := &in.RPCPingTimeout, &out.RPCPingTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RPCTimeout != nil {
		in, out := &in.RPCTimeout, &out.RPCTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePortEndpointConfig) DeepCopyInto(out *NodePortEndpointConfig) {
	*out = *in
	in.ServiceMeta.DeepCopyInto(&out.ServiceMeta)
	if in.ExternalAddresses != nil {
		in, out := &in.ExternalAddresses, &out.ExternalAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePortEndpointConfig.
func (in *NodePortEndpointConfig) DeepCopy() *NodePortEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(NodePortEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeScrubStatus) DeepCopyInto(out *NodeScrubStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeScrubStatus.
func (in *NodeScrubStatus) DeepCopy() *NodeScrubStatus {
	if in == nil {
		return nil
	}
	out := new(NodeScrubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DataDiskAvailable != nil {
		in, out := &in.DataDiskAvailable, &out.DataDiskAvailable
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DataDiskTotal != nil {
		in, out := &in.DataDiskTotal, &out.DataDiskTotal
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MetadataDiskAvailable != nil {
		in, out := &in.MetadataDiskAvailable, &out.MetadataDiskAvailable
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MetadataDiskTotal != nil {
		in, out := &in.MetadataDiskTotal, &out.MetadataDiskTotal
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRetentionPolicy) DeepCopyInto(out *PVCRetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRetentionPolicy.
func (in *PVCRetentionPolicy) DeepCopy() *PVCRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(PVCRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudgetConfig) DeepCopyInto(out *PodDisruptionBudgetConfig) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudgetConfig.
func (in *PodDisruptionBudgetConfig) DeepCopy() *PodDisruptionBudgetConfig {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudgetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplate) DeepCopyInto(out *PodTemplate) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTemplate.
func (in *PodTemplate) DeepCopy() *PodTemplate {
	if in == nil {
		return nil
	}
	out := new(PodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicEndpointConfig) DeepCopyInto(out *PublicEndpointConfig) {
	*out = *in
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(LoadBalancerEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(NodePortEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(ExternalIPEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicEndpointConfig.
func (in *PublicEndpointConfig) DeepCopy() *PublicEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(PublicEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterConfig) DeepCopyInto(out *RemoteClusterConfig) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
	if in.DefaultCapacity != nil {
		in, out := &in.DefaultCapacity, &out.DefaultCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterConfig.
func (in *RemoteClusterConfig) DeepCopy() *RemoteClusterConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterConnection) DeepCopyInto(out *RemoteClusterConnection) {
	*out = *in
	if in.AdminTokenSecretRef != nil {
		in, out := &in.AdminTokenSecretRef, &out.AdminTokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterConnection.
func (in *RemoteClusterConnection) DeepCopy() *RemoteClusterConnection {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterStatus) DeepCopyInto(out *RemoteClusterStatus) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterStatus.
func (in *RemoteClusterStatus) DeepCopy() *RemoteClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepairStatus) DeepCopyInto(out *RepairStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepairStatus.
func (in *RepairStatus) DeepCopy() *RepairStatus {
	if in == nil {
		return nil
	}
	out := new(RepairStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationConfig) DeepCopyInto(out *ReplicationConfig) {
	*out = *in
	if in.ZoneRedundancyMinZones != nil {
		in, out := &in.ZoneRedundancyMinZones, &out.ZoneRedundancyMinZones
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationConfig.
func (in *ReplicationConfig) DeepCopy() *ReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(ReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3APIConfig) DeepCopyInto(out *S3APIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3APIConfig.
func (in *S3APIConfig) DeepCopy() *S3APIConfig {
	if in == nil {
		return nil
	}
	out := new(S3APIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScrubStatus) DeepCopyInto(out *ScrubStatus) {
	*out = *in
	if in.LastCompleted != nil {
		in, out := &in.LastCompleted, &out.LastCompleted
		*out = (*in).DeepCopy()
	}
	if in.NextRun != nil {
		in, out := &in.NextRun, &out.NextRun
		*out = (*in).DeepCopy()
	}
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make([]NodeScrubStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScrubStatus.
func (in *ScrubStatus) DeepCopy() *ScrubStatus {
	if in == nil {
		return nil
	}
	out := new(ScrubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	in.ServiceMeta.DeepCopyInto(&out.ServiceMeta)
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMeta) DeepCopyInto(out *ServiceMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMeta.
func (in *ServiceMeta) DeepCopy() *ServiceMeta {
	if in == nil {
		return nil
	}
	out := new(ServiceMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(VolumeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(VolumeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCRetentionPolicy != nil {
		in, out := &in.PVCRetentionPolicy, &out.PVCRetentionPolicy
		*out = new(PVCRetentionPolicy)
		**out = **in
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PodDisruptionBudgetConfig)
		(*in).DeepCopyInto(*out)
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CertSecretRef != nil {
		in, out := &in.CertSecretRef, &out.CertSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KeySecretRef != nil {
		in, out := &in.KeySecretRef, &out.KeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeConfig) DeepCopyInto(out *VolumeConfig) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VolumeClaimTemplateSpec != nil {
		in, out := &in.VolumeClaimTemplateSpec, &out.VolumeClaimTemplateSpec
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]DataPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeConfig.
func (in *VolumeConfig) DeepCopy() *VolumeConfig {
	if in == nil {
		return nil
	}
	out := new(VolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAPIConfig) DeepCopyInto(out *WebAPIConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAPIConfig.
func (in *WebAPIConfig) DeepCopy() *WebAPIConfig {
	if in == nil {
		return nil
	}
	out := new(WebAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerError) DeepCopyInto(out *WorkerError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerError.
func (in *WorkerError) DeepCopy() *WorkerError {
	if in == nil {
		return nil
	}
	out := new(WorkerError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkersConfig) DeepCopyInto(out *WorkersConfig) {
	*out = *in
	if in.ScrubTranquility != nil {
		in, out := &in.ScrubTranquility, &out.ScrubTranquility
		*out = new(int32)
		**out = **in
	}
	if in.ResyncWorkerCount != nil {
		in, out := &in.ResyncWorkerCount, &out.ResyncWorkerCount
		*out = new(int32)
		**out = **in
	}
	if in.ResyncTranquility != nil {
		in, out := &in.ResyncTranquility, &out.ResyncTranquility
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkersConfig.
func (in *WorkersConfig) DeepCopy() *WorkersConfig {
	if in == nil {
		return nil
	}
	out := new(WorkersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkersStatus) DeepCopyInto(out *WorkersStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]WorkerError, len(*in))
		copy(*out, *in)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkersStatus.
func (in *WorkersStatus) DeepCopy() *WorkersStatus {
	if in == nil {
		return nil
	}
	out := new(WorkersStatus)
	in.DeepCopyInto(out)
	return out
}
