#!/usr/bin/env python3
"""Render the served CRD schemas (generated from Go by controller-gen) as Markdown."""

import argparse
import json
import re
import sys
from pathlib import Path

import yaml


def cell(value):
    """Keep Markdown table cells on one line without losing source prose."""
    value = re.sub(r"\s+", " ", str(value)).strip()
    return value.replace("|", r"\|").replace("[", r"\[").replace("]", r"\]")


def field_type(schema):
    if not isinstance(schema, dict):
        return "any"
    kind = schema.get("type")
    if kind == "array":
        kind = f"array of {field_type(schema.get('items', {}))}"
    elif kind == "object":
        if "additionalProperties" in schema:
            kind = f"map of {field_type(schema['additionalProperties'])}"
        else:
            kind = "object"
    elif not kind and "anyOf" in schema:
        kind = " or ".join(dict.fromkeys(field_type(part) for part in schema["anyOf"]))
    elif not kind:
        kind = "any"
    if schema.get("nullable"):
        kind += " (nullable)"
    return kind


def constraints(schema, required):
    parts = ["required"] if required else []
    for key, label in (
        ("default", "default"),
        ("enum", "enum"),
        ("format", "format"),
        ("minimum", "min"),
        ("maximum", "max"),
        ("minLength", "min length"),
        ("maxLength", "max length"),
        ("minItems", "min items"),
        ("maxItems", "max items"),
        ("pattern", "pattern"),
    ):
        if key in schema:
            parts.append(f"{label}: {json.dumps(schema[key], ensure_ascii=False, sort_keys=True)}")
    for rule in schema.get("x-kubernetes-validations", []):
        if rule.get("message"):
            parts.append(f"validation: {rule['message']}")
    return "; ".join(parts)


def fields(schema, prefix=""):
    required = set(schema.get("required", []))
    for name, child in sorted(schema.get("properties", {}).items()):
        path = f"{prefix}.{name}" if prefix else name
        yield path, child, name in required
        yield from fields(child, path)
    items = schema.get("items")
    if isinstance(items, dict):
        yield from fields(items, prefix + "[]")
    values = schema.get("additionalProperties")
    if isinstance(values, dict):
        yield from fields(values, prefix + ".*")


def render_section(name, schema):
    lines = [f"## {name}", ""]
    if not schema:
        return lines + ["No typed fields are published for this section.", ""]
    if schema.get("description"):
        lines.extend([cell(schema["description"]), ""])
    rows = list(fields(schema))
    if rows:
        lines.extend(
            [
                "| Field path | Type | Constraints | Description |",
                "| --- | --- | --- | --- |",
            ]
        )
        for path, field, required in rows:
            lines.append(
                f"| `{path}` | {cell(field_type(field))} | "
                f"{cell(constraints(field, required))} | {cell(field.get('description', ''))} |"
            )
        lines.append("")
    rules = schema.get("x-kubernetes-validations", [])
    if rules:
        lines.extend(["### Cross-field validation", ""])
        for rule in rules:
            message = rule.get("message", "Validation rule")
            lines.extend([f"- {cell(message)}: `{rule['rule']}`", ""])
    return lines


def render_resource(crd, version):
    kind = crd["spec"]["names"]["kind"]
    group = crd["spec"]["group"]
    schema = version.get("schema", {}).get("openAPIV3Schema", {})
    properties = schema.get("properties", {})
    lines = [
        f"# {kind} {version['name']}",
        "",
        "<!-- Generated by hack/generate_api_reference.py from controller-gen CRDs. Do not edit. -->",
        "",
        f"API version: `{group}/{version['name']}`. Scope: {crd['spec']['scope']}.",
        "",
        "The [custom-resource guide](../custom-resources.md) explains operational behavior. "
        "The [JSON schemas](../samples.md) are the validation source of truth.",
        "",
    ]
    if version.get("deprecated"):
        lines.extend(["This served version is deprecated; use a newer version for new resources.", ""])
    if kind == "GarageBucket" and version["name"] == "v1alpha1":
        lines.extend([
            "This compatibility version's schema is preserved from the historical CRD. "
            "Current version schemas are generated from the Go API types.",
            "",
        ])
    if not properties.get("spec") and not properties.get("status"):
        lines.extend(
            ["This compatibility version has no typed spec or status schema. "
             "Use the current API version for new resources.", ""]
        )
    else:
        lines.extend(render_section("Spec", properties.get("spec")))
        lines.extend(render_section("Status", properties.get("status")))
    return "\n".join(lines).rstrip() + "\n"


def render_index(entries):
    lines = [
        "# Generated API reference",
        "",
        "<!-- Generated by hack/generate_api_reference.py from controller-gen CRDs. Do not edit. -->",
        "",
        "These field tables come from the CRD schemas. Current version schemas are "
        "generated from the Go API types; the served GarageBucket v1alpha1 schema "
        "is preserved for compatibility. "
        "Run `make api-reference` after editing those types. "
        "The [custom-resource guide](../custom-resources.md) adds usage and safety guidance.",
        "",
        "| Kind | Served version | Scope |",
        "| --- | --- | --- |",
    ]
    for kind, version, scope, filename in entries:
        lines.append(f"| {kind} | [{version}]({filename}) | {scope} |")
    return "\n".join(lines) + "\n"


def generate(crd_dir):
    pages = {}
    entries = []
    for path in sorted(crd_dir.glob("*.yaml")):
        crd = yaml.safe_load(path.read_text())
        if crd.get("kind") != "CustomResourceDefinition":
            continue
        kind = crd["spec"]["names"]["kind"]
        for version in crd["spec"]["versions"]:
            if not version.get("served"):
                continue
            filename = f"{kind.lower()}-{version['name']}.md"
            pages[filename] = render_resource(crd, version)
            entries.append((kind, version["name"], crd["spec"]["scope"], filename))
    if not entries:
        raise ValueError(f"No served CRD versions found in {crd_dir}")
    pages["index.md"] = render_index(sorted(entries))
    return pages


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--crd-dir", type=Path, default=Path("config/crd/bases"))
    parser.add_argument("--output-dir", type=Path, default=Path("docs/reference/api"))
    parser.add_argument("--check", action="store_true", help="fail if committed pages are stale")
    args = parser.parse_args(argv)
    pages = generate(args.crd_dir)
    existing = {p.name for p in args.output_dir.glob("*.md")}
    stale = sorted(name for name, content in pages.items()
                   if not (args.output_dir / name).exists()
                   or (args.output_dir / name).read_text() != content)
    extra = sorted(existing - pages.keys())
    if args.check:
        if stale or extra:
            for name in stale:
                print(f"Stale or missing API reference: {args.output_dir / name}", file=sys.stderr)
            for name in extra:
                print(f"Unexpected API reference: {args.output_dir / name}", file=sys.stderr)
            print("Run 'make api-reference' and commit the result.", file=sys.stderr)
            return 1
        print("Generated API reference is current.")
        return 0
    if extra:
        for name in extra:
            print(f"Remove obsolete generated page: {args.output_dir / name}", file=sys.stderr)
        return 1
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in pages.items():
        (args.output_dir / name).write_text(content)
    print(f"Generated {len(pages)} API reference pages in {args.output_dir}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
