## Append samples of your project ##
resources:
- garage_v1beta1_garagecluster.yaml
- garage_v1beta1_garagecluster_gateway.yaml
- garage_v1beta1_garagebucket.yaml
- garage_v1beta1_garagebucket_cross_namespace.yaml
- garage_v1beta1_garagekey.yaml
- garage_v1beta1_garagenode.yaml
- garage_v1beta1_garagenode_maintenance.yaml
- garage_v1beta1_garageadmintoken.yaml
- garage_v1beta1_garagereferencegrant.yaml
- garage_v1beta2_garagecluster_auto_per_node.yaml
- garage_v1beta2_garagecluster_eject_to_manual.yaml
- garage_v1beta2_garagecluster_management_handle.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
