## Append samples of your project ##
resources:
- garage_v1beta1_garagecluster.yaml
- garage_v1beta1_garagecluster_gateway.yaml
- garage_v1beta1_garagebucket.yaml
- garage_v1beta1_garagekey.yaml
- garage_v1beta1_garagenode.yaml
- garage_v1beta1_garageadmintoken.yaml
- garage_v1beta1_garagereferencegrant.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
